### ISSUE TITLE
MaterialFrame with SVG shows white screen

### ISSUE THREAD

**Issue by mauro-dasilva** [roubachof/Sharpnado.MaterialFrame#5] opened 2020-05-08 05:39 UTC
**Platform (please complete the following information):**
 - OS: Android (Not sure about iOS)
 - Device: AndroidEmulator/Pixel 2 XL
 - Sdk vervion: Android SDK 28
 - Xamarin.Forms: [4.6.0.726]

**Describe the bug**
When you navigate to a page that has a SVG Image inside the MaterialFrame, the screen goes all white. However, when you navigate back and go back to that screen it shows correctly. This only happens if you have the `MaterialTheme `set to `AcrylicBlur`, all other themes seem to work correctly.

**To Reproduce**
I have attached a sample project which replicates the issue, in addition to a clip showing the issue.

1. Click on any of the list items on the main page
2. It will navigate to the Details page for the item and an SVG image should be shown, however nothing is displayed
3. Press the back button (You will see the image flash for a second)
4. Click on the same item again to view its detail. This time page loads correctly and the image is shown

**Screenshots (if applicable)**
See attached screen capture
![Issue](https://user-images.githubusercontent.com/37144094/81374167-33667880-9131-11ea-931a-d1583e692529.gif)

[App1.zip](https://github.com/roubachof/Sharpnado.MaterialFrame/files/4597153/App1.zip)

**Comment by roubachof** [comment] 2020-05-08 06:56
Have you tried increasing the AndroidMaterialFrameRenderer.BlurProcessDelayMilliseconds property ?
Maybe try something crazy like 1000 ms and if it works lower the value till finding a good value

**Comment by mauro-dasilva** [comment] 2020-05-08 07:18
Just tried that out and even tried 10 seconds, but it is still having the same issue.

**Comment by roubachof** [comment] 2020-05-08 10:34
found out that the `BlurProcessingDelay` had a bad semantic. This will be fixed in the next version.
The issue is that the computation of the svg is super slow, so the blur algo is confused and messes the ui hierarchy. You will probably need to set the `BlurProcessingDelay` to 100ms to have a good result when the next version will be released.

**Comment by mauro-dasilva** [comment] 2020-05-08 11:12
Perfect! Thanks very much for that.

**Comment by mauro-dasilva** [comment] 2020-05-09 02:18
Another question, would that affect iOS as well?

**Closed as completed** 2020-06-07 06:41 UTC
Labels: bug
